# site name
name: marco.io

# use redcarpet for markdown
markdown: redcarpet

# redcarpet extensions
redcarpet:
  extensions: ["tables"]

# permalink structure
permalink: /:categories/:year/:month/:day/:title

# Bootstrap Theme
bootstrap-theme: readable
