# site name
name: marco.io

# use redcarpet for markdown
markdown: redcarpet

# redcarpet extensions
redcarpet:
  extensions: ["tables"]

# permalink structure
# same as /:categories/:year/:month/:day/:title
permalink: pretty

# Bootstrap Theme
bootstrap_theme: cosmo

pygments: true

# Category Title Prefix
category_title_prefix: ''